# Generated by Django 2.2.5 on 2019-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='credit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
