# Generated by Django 2.2.5 on 2019-09-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-upload_date', '-modify_date'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-upload_date', '-modify_date'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-upload_date', '-modify_date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
